---
- name: Create datadir if it does not exist
  file:
    path: "{{ mysql_datadir }}"
    state: directory
    owner: mysql
    group: mysql
    mode:  0755

- name: Ensure MySQL is started and enabled on boot.
  service: "name={{ mysql_daemon }} state=started enabled=yes"

- name: Set root Password
  mysql_user: login_password={{ mysql_root_password }} check_implicit_admin=yes name=root host={{ item }} password={{ mysql_root_password }} state=present 
  with_items:
    - localhost
    - 127.0.0.1
    - ::1

- name: Copy my.cnf 
  template:
    src="templates/my.cfn.j2" dest="/etc/my.cfn" owner=root mode=0600 
  notify: restart_mysql

- name: Remove all anonymous user accounts
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: ''
    host_all: yes
    state: absent

- name: Remove the MySQL test database
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root_password }}" 
    db: test 
    state: absent

- name: Create MySQL database
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    db: "{{ mysql_database }}"
    state: present
  when: mysql_database is defined


- name: Create user
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: "{{ mysql_user }}"
    password: "{{ mysql_user_password }}"
    host: "%"
    priv: '*.*:ALL,GRANT'
    state: present
  when: mysql_user is defined
